=== Interprocess Communication

Linux supports some mechanisms to allow comunication between processes and between process and kernel.
Here will be the list of the IPC examples and some examples

==== Signals
Signaling asynchronous event to one and more processes. Unix operating system maintain *two integers* for *pending signals* and *blocked signals* .
There are two types if signal handlers:
* Default signal handler
* User Defined Signal handler

The available list of signals can be generated by:
----
kill -l
----
the output on macOS is:
----
HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
----
Some signals can be ignored except SIGSTOP and SIGKILL.
Normally processes can send signals to the processes with the same *uid* and *gid* or the process with the same process group. Kernel and super user can send signal to everybody.










=== References
 * Linux Documentation link:https://tldp.org/LDP/tlk/ipc/ipc.html[link]

