=== Interprocess Communication

Linux supports some mechanisms to allow comunication between processes and between process and kernel.
Here will be the list of the IPC examples and some examples

==== Signals

Linux supports:

* POSX Reliable Signals (Standard Signals)
** SIGKILL (Term)
** SIGSTOP (Stop)
** SIGABRT (Core)

* POSX Real-Time Signals (queued, in guaraneed order)
** SIGRTMIN
** All signals can be used for application purposes
** SIGRTMAX

*Signals dispositions* are same for all threads in the process and can be cloned by *fork()*:

* Term - default action is to terminate process
* Ign - default action is to ignore signal
* Core - default action is to terminate process and do the core dump
* Stop - defualt aciton is to stop the process
* Cont - defualt action is to continue process if currently stoped

Unix operating system maintain signals by two integers:

* blocked signals (they appear not deliveared so looks pending)
* pending signals

The signals can be targeted like:

* process-directed
* thread-directed

There are two types if signal handlers:
* Default signal handler
* User Defined Signal handler

The available list of signals can be generated by:
----
kill -l
----
the output on macOS is:
----
HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
----
Some signals can be ignored except SIGSTOP and SIGKILL.
Normally processes can send signals to the processes with the same *uid* and *gid* or the process with the same process group. Kernel and super user can send signal to everybody.










=== References
 * Linux Documentation link:https://tldp.org/LDP/tlk/ipc/ipc.html[link]
 * Singnal description in Manual link:https://man7.org/linux/man-pages/man7/signal.7.html[link]

